#!/usr/bin/env python3
"""
Generate doc/generated/validation-measured.md from benchmark results files.

The measured levels in the documentation are written by the harness that measured them,
not maintained by hand. Run the benchmark on each build with --results, then point this
script at both files.

The output is deterministic: same results in, same bytes out. Nothing time dependent,
machine dependent or path dependent is written, because the keystone regenerates this
file and requires the diff to be empty. A timestamp would fail that check on every run
and the check would be abandoned, which is how generated documentation goes stale.

Usage:

  report_validation.py --debug <results> --production <results> --out <file.md>

The results files are written by run_fel_benchmark.sh --results, one record per line:

  build|<flavor>
  section|<name>|<outcome>
  tier|<key>|<level>|<outcome>|<description>
"""

import argparse
import sys
from pathlib import Path


def read_results(path):
    """Parse one results file into {'build':…, 'sections':[…], 'tiers':[…]}."""
    out = {"build": None, "sections": [], "tiers": []}
    for line in Path(path).read_text().splitlines():
        if not line.strip():
            continue
        kind, _, rest = line.partition("|")
        f = rest.split("|")
        if kind == "build":
            out["build"] = f[0]
        elif kind == "section":
            out["sections"].append((f[0], f[1]))
        elif kind == "tier":
            out["tiers"].append({"key": f[0], "level": f[1], "outcome": f[2],
                                 "desc": f[3] if len(f) > 3 else ""})
        else:
            raise SystemExit(f"{path}: unknown record kind {kind!r}")
    if out["build"] is None:
        raise SystemExit(f"{path}: no build record")
    return out


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--debug", required=True, help="Results file from the debug build")
    p.add_argument("--production", required=True, help="Results file from the production build")
    p.add_argument("--out", required=True, help="Markdown file to write")
    args = p.parse_args()

    dbg = read_results(args.debug)
    prod = read_results(args.production)

    for got, want, path in ((dbg["build"], "debug", args.debug),
                            (prod["build"], "production", args.production)):
        if got != want:
            raise SystemExit(f"{path}: expected a {want} build, got {got!r}")

    dkeys = [t["key"] for t in dbg["tiers"]]
    pkeys = [t["key"] for t in prod["tiers"]]
    if dkeys != pkeys:
        raise SystemExit(f"tier sets differ between builds:\n  debug {dkeys}\n  production {pkeys}")

    plevel = {t["key"]: t["level"] for t in prod["tiers"]}
    poutcome = {t["key"]: t["outcome"] for t in prod["tiers"]}

    L = []
    L.append("<!-- Generated by tests/scripts/report_validation.py. Do not edit. -->")
    L.append("")
    L.append("The tiers, as measured on the build that ran. A digit here moves only when the")
    L.append("physics moves, and the keystone regenerates this file and requires no diff.")
    L.append("")
    L.append("| Tier | What runs | Debug | Production |")
    L.append("|---|---|---|---|")
    for t in dbg["tiers"]:
        k = t["key"]
        mark = "" if t["outcome"] == "pass" and poutcome[k] == "pass" else " (FAILING)"
        same = t["level"] == plevel[k]
        prod_cell = "same" if same else plevel[k]
        L.append(f"| `{k}` | {t['desc']} | {t['level']}{mark} | {prod_cell} |")
    L.append("")
    L.append('Production levels read "same" where the two builds agree to every printed digit.')
    L.append("Debug and production binaries are never bit-comparable to each other, so the")
    L.append("columns are two independent records rather than a comparison.")
    L.append("")
    L.append("## Check sections")
    L.append("")
    L.append(f"Every section below ran and passed on both builds, {len(dbg['sections'])} in all.")
    L.append("A section that fails stops the run, so an entry here means it passed.")
    L.append("")
    dsec = [s for s, _ in dbg["sections"]]
    psec = [s for s, _ in prod["sections"]]
    if dsec != psec:
        raise SystemExit(f"section sets differ between builds:\n  debug {dsec}\n  production {psec}")
    for s in dsec:
        L.append(f"- `{s}`")
    L.append("")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(L))
    print(f"wrote {args.out}: {len(dbg['tiers'])} tiers, {len(dsec)} check sections")
    return 0


if __name__ == "__main__":
    sys.exit(main())
