#!/usr/bin/env python3
"""
Generate doc/generated/api.md from the source's own routine headers.

Bmad documents a routine in a `!+ ... !-` block above it, and util/getf reads exactly
that convention. This script reads the same blocks out of the FEL sources, so the API
reference is the code's own headers rather than a second description that can drift from
them. Nothing here is written by hand, and the keystone regenerates the file and
requires an empty diff.

Deterministic by construction: files in sorted order, entries in source order, no
timestamp and no path outside the tree.

Usage:

  report_api.py --code <dir> [--code <dir>] --out <file.md>
"""

import argparse
import re
import sys
from pathlib import Path

# The header conventions actually present in this tree, including the variants:
# "Structure" beside "Struct", and "Program" for the driver.
KINDS = ("Module", "Subroutine", "Function", "Structure", "Struct", "Interface", "Program")


def slug(name):
    return "api-" + re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def parse_file(path):
    """Yield {kind, name, signature, prose, args} for each !+ ... !- header block."""
    lines = path.read_text().splitlines()
    i = 0
    while i < len(lines):
        if lines[i].strip() != "!+":
            i += 1
            continue
        j = i + 1
        block = []
        while j < len(lines) and lines[j].strip() != "!-":
            block.append(re.sub(r"^!\s?", "", lines[j]).rstrip())
            j += 1
        i = j + 1
        if not block:
            continue
        head = next((b for b in block if b.strip()), "")
        m = re.match(r"\s*(" + "|".join(KINDS) + r")\s+([A-Za-z0-9_%<>]+)\s*(\(.*)?$", head)
        if not m:
            continue                      # a comment banner that is not an entity header
        kind, name, sig = m.group(1), m.group(2), (m.group(3) or "").strip()
        rest = block[block.index(head) + 1:]
        # Split the prose from the Input:/Output: argument blocks.
        cut = len(rest)
        for k, b in enumerate(rest):
            if re.match(r"\s*(Input|Output|Returns?)\s*:", b):
                cut = k
                break
        prose = "\n".join(rest[:cut]).strip("\n")
        args = "\n".join(rest[cut:]).strip("\n")
        yield {"kind": kind, "name": name, "sig": sig, "prose": prose, "args": args}


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--code", action="append", required=True, help="Directory of .f90 sources")
    p.add_argument("--out", required=True)
    args = p.parse_args()

    files = sorted({f for d in args.code for f in Path(d).glob("*.f90")},
                   key=lambda f: f.name)
    if not files:
        raise SystemExit("no .f90 sources found")

    L = []
    L.append("---")
    L.append("title: API reference")
    L.append("short_title: API reference")
    L.append("---")
    L.append("")
    L.append("<!-- Generated by tests/scripts/report_api.py from the source headers. Do not edit. -->")
    L.append("")
    L.append("Every module, routine and structure, from the `!+ ... !-` headers in the source.")
    L.append("This page is generated, so it says what the code says. `util/getf <name>` prints the")
    L.append("same header at a terminal.")
    L.append("")

    total = 0
    for f in files:
        entries = list(parse_file(f))
        if not entries:
            continue
        L.append(f"## `{f.name}`")
        L.append("")
        for e in entries:
            total += 1
            L.append(f"({slug(e['name'])})=")
            title = f"`{e['name']}`"
            L.append(f"### {title}")
            L.append("")
            L.append(f"*{e['kind']}*" + (f" `{e['sig']}`" if e["sig"] else ""))
            L.append("")
            if e["prose"]:
                L.append("```")
                L.append(e["prose"])
                L.append("```")
                L.append("")
            if e["args"]:
                L.append("```")
                L.append(e["args"])
                L.append("```")
                L.append("")

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(L))
    print(f"wrote {args.out}: {total} entries from {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
